### ISSUE TITLE
Some questions...

### ISSUE THREAD

**Issue by circle241** [StevenCyb/VideoComparison#1]
is this project a study project without the esseantial parts?
Cause it has not pom.xml, ffmpeg and opencv libs...
I wanna study the area.
so sad....

**Comment by StevenCyb** [comment]
Hi Xiaoyu,

this was just a project for fun. There are still some bugs and the usability is bad. 
To be honest, I'm even not sure if it's a good solution to compare videos. It was just an spontaneous idea which I wanted to try.

I did not include any library (ffmpeg, opencv) because they depend on the arch. You need to install them for your os. You can find the required files in `LibraryLoader.java`.

If you have some problems, I might find some time to help you.

Greetings

**Comment by circle241** [comment]
tks, boy.
I change to use javacv to complete this.
(plus, this project is the only one opensource for videoComparison.
maybe i will make another?)

**Comment by StevenCyb** [comment]
Sure, I look forward to see your result.

**Comment by StevenCyb** [comment]
Feel free to link your reults.
